Controllers/PhysiosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Physiosoft.Data;
using Physiosoft.Logger;

namespace Physiosoft.Controllers
{
    public class PhysiosController : Controller
    {
        private readonly PhysiosoftDbContext _context;

        public PhysiosController(PhysiosoftDbContext context)
        {
            _context = context;
        }

        // GET: Physios
        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await _context.Physios.ToListAsync());
            } 
            catch (Exception ex)
            {
                NLogger.LogError($"Error! Ex: {ex.Message}");
                return StatusCode(500); // Return a status code indicating an internal server error
            }
            
        }

        // GET: Physios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                NLogger.LogError($"ID for physio was null in details view.");
                return NotFound();
            }

            var physio = await _context.Physios
                .FirstOrDefaultAsync(m => m.PhysioId == id);

            if (physio == null)
            {
                NLogger.LogError($"Physio with id: {id} was not found in details view.");
                return NotFound();
            }

            NLogger.LogInfo($"Returning physio with id {id} in details view");
            return View(physio);
        }


        // GET: Physios/Create
        public IActionResult Create()
        {
            return View(new Physio());
        }

        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Physio request)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var physio = new Physio
                    {
                        Firstname = request.Firstname,
                        Lastname = request.Lastname,
                        Telephone = request.Telephone
                    };

                    _context.Add(physio);
                    await _context.SaveChangesAsync();
                    NLogger.LogInfo($"Succesfully created and saved Physio, redirecting to action now.");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                                         .Select(e => e.ErrorMessage);

                    var errors = ModelState
                    .Select(kvp => new { Key = kvp.Key, Errors = kvp.Value.Errors.Select(e => e.ErrorMessage) });

                    foreach (var error in errors)
                    {
                        foreach (var errorMessage in error.Errors)
                        {
                            NLogger.LogError($"Key: {error.Key}, Error: {errorMessage}");
                        }
                    }
                    NLogger.LogInfo($"Returning Physio Create view with errors.");
                    return View(request);
                }
            }
            catch (DbUpdateException ex)
            {
                if (IsUniqueConstraintViolation(ex))
                {
                    string duplicateColumn = GetDuplicateColumn(ex);
                    NLogger.LogError($"Duplicate value Error {duplicateColumn} occurred while editing a physio entity. Ex: {ex.Message}");
                    ModelState.AddModelError(duplicateColumn, $"The {duplicateColumn} field is required.");
                    return View(request);
                }
                else
                {
                    NLogger.LogError($"Error in physio create! Exception: {ex.Message}");
                    return StatusCode(500);
                }
            }
            catch (Exception ex)
            {
                NLogger.LogError($"Error! Exception: {ex.Message}");
                return StatusCode(500);
            }
        }

        // GET: Physios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                NLogger.LogError($"ID in Physio EDIT was null.");
                return NotFound();
            }

            var physio = await _context.Physios.FindAsync(id);

            if (physio == null)
            {
                NLogger.LogError($"Physio in EDIT with id {id} was NOT found.");
                return NotFound();
            }
           
            return View(physio);
        }

        // POST: Physios/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PhysioId,Firstname,Lastname,Telephone")] Physio physio)
        {
            if (id != physio.PhysioId)
            {
                NLogger.LogError($"Physio in EDIT with id {physio.PhysioId} doesnt match the given ID: {id}");
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(physio);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch(DbUpdateException ex)
                {
                    if (IsUniqueConstraintViolation(ex))
                    {
                        string duplicateColumn = GetDuplicateColumn(ex);
                        NLogger.LogError($"Duplicate value Error {duplicateColumn} occurred while editing a physio entity. Ex: {ex.Message}");
                        ModelState.AddModelError(duplicateColumn, $"The {duplicateColumn} field is required.");
                        return View(physio);
                    }
                    else
                    {
                        NLogger.LogError($"Error in physio create! Exception: {ex.Message}");
                        return StatusCode(500);
                    }
                }     
                catch(Exception ex)
                {
                    ModelState.AddModelError("", "An Error has occured.");
                    NLogger.LogError($"Error occurred while editing a physios entity. Ex: {ex.Message}");
                    return StatusCode(500);
                }
            }
            else
            {
                var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                                     .Select(e => e.ErrorMessage);

                var errors = ModelState
                .Select(kvp => new { Key = kvp.Key, Errors = kvp.Value.Errors.Select(e => e.ErrorMessage) });

                foreach (var error in errors)
                {
                    foreach (var errorMessage in error.Errors)
                    {
                        NLogger.LogError($"Key: {error.Key}, Error: {errorMessage}");
                    }
                }
                return View(physio);
            }
        }

        // GET: Physios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var physio = new Physio();
            if (id == null)
            {
                NLogger.LogError($"ID in Physio Delete was null.");
                return NotFound();
            }
            try
            {
                physio = await _context.Physios
                .FirstOrDefaultAsync(m => m.PhysioId == id);
                if (physio == null)
                {
                    NLogger.LogError($"Physio in Delete with id {id} was NOT found and returned null.");
                    return NotFound();
                }
            }
            catch (DbUpdateException ex)
            {
                NLogger.LogError($"Database update exception in physios delete: {ex.Message}");
                return StatusCode(500);
            }
            catch (Exception ex) 
            {
                NLogger.LogError($"Error in physios delete! Exception: {ex.Message}");
                return StatusCode(500);
            }
            
            return View(physio);       
        }

        // POST: Physios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var physio = await _context.Physios.FindAsync(id);
                if (physio != null)
                {
                    _context.Physios.Remove(physio);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    NLogger.LogError($"Physio with id {id} in Delete was not found.");
                    return NotFound(); 
                }
            }
            catch (DbUpdateConcurrencyException ex)
            {
                NLogger.LogError($"Concurrency error occurred in DeleteConfirmed: {ex.Message}");
                return StatusCode(500);
            }
            catch (DbUpdateException ex)
            {
                NLogger.LogError($"Database update error occurred in DeleteConfirmed: {ex.Message}");
                return StatusCode(500); 
            }
            catch (Exception ex)
            {
                NLogger.LogError($"Error in DeleteConfirmed: {ex.Message}");
                return StatusCode(500); 
            }


            return RedirectToAction(nameof(Index));
        }

        private bool PhysioExists(int id)
        {
            return _context.Physios.Any(e => e.PhysioId == id);
        }

        [HttpGet]
        public async Task<IActionResult> GetPhysioLastName(int id)
        {
            var physio = await _context.Physios.FindAsync(id);

Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Physiosoft.Data;
using Physiosoft.DTO.User;
using Physiosoft.Repisotories;
using Physiosoft.Logger;

namespace Physiosoft.Controllers
{
    // TODO RESOLVE USER REPOISTORY
    public class UsersController : Controller
    {
        private readonly PhysiosoftDbContext _context;
        private readonly IUserRepository _userRepository;

        public UsersController(PhysiosoftDbContext context, IUserRepository userRepository)
        {
            _context = context;
            _userRepository = userRepository;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            //return View(await _context.Users.ToListAsync());
            var users = await _context.Users.ToListAsync();
            var userDTOs = users.Select(users => new UserUtilDTO
            {
                UserId = users.UserId,
                Username = users.Username,
                Email = users.Email,
            }).ToList();

            return View(userDTOs);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                NLogger.LogError($"Error! Given ID was null");
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                NLogger.LogError($"Error! Didnt find user with ID: {id}");
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View(new UserSignupDTO());
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserSignupDTO request)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool signupSuccess = await _userRepository.SignupUserAsync(request);
                    if (signupSuccess)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("", "User already exists.");
                    }
                }
            }
            catch (DbUpdateException ex)
            {
                if (IsUniqueConstraintViolation(ex))
                {
                    ModelState.AddModelError("", "The entered value already exists. Please use a unique value.");
                    NLogger.LogError($"Duplicate value error. Error: {ex.Message}");
                }
                else
                {
                    NLogger.LogError($"Error occurred while signing up a user entity. Ex: {ex.Message}");
                }
            }
            catch (Exception ex)
            {
                NLogger.LogError($"Error occurred while signing up a user entity. Ex: {ex.Message}");
            }

            return View(request);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                NLogger.LogError($"ID in User EDIT was null.");
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                NLogger.LogError($"User in EDIT with id {id} was NOT found.");
                return NotFound();
            }

            var userPatchDTO = new UserPatchDTO
            {
                Username = user.Username,
                Email = user.Email,
                Password = user.Password,
            };

            return View(userPatchDTO);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("UserId,Username,Password,Email")] User user)
        public async Task<IActionResult> Edit(int id, UserPatchDTO request)
        {
            if(!ModelState.IsValid)
            {
                return View(request);
            }

            var user = await _context.Users.FindAsync(id);
            if(user == null) 
            {
                NLogger.LogError($"User in EDIT with id {id} was NOT found.");
                return NotFound();
            }

            user.Username = request.Username!;
            user.Email = request.Email!;
            user.Password = request.Password!;

            try
            {
                _context.Update(user);
                await _context.SaveChangesAsync();
            }
            catch(DbUpdateConcurrencyException)
            {
                if (!UserExists(user.UserId))
                {
                    NLogger.LogError($"Errorm user with id: {user.UserId} doesnt exist!");
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            catch(Exception ex)
            {
                NLogger.LogError($"Error! {ex.Message}");
            }
            return RedirectToAction(nameof(Index));
        }
         
        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                NLogger.LogError($"Given ID was null");
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                NLogger.LogError($"User in EDIT with id {id} was NOT found.");
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }else
            {
                NLogger.LogError($"User in EDIT with id {id} was NOT found.");
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }

        private bool IsUniqueConstraintViolation(DbUpdateException ex)
        {
            // Check if the exception is due to a unique constraint violation
            return ex.InnerException?.Message.Contains("unique constraint") ?? false;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Physiosoft</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Physiosoft.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Physiosoft</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <!-- Hamburger Menu -->
                        @if (User.Identity.IsAuthenticated)
                        {
                            <!-- Hamburger Menu for Admin -->
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    CRUD
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Physios" asp-action="Index">Physios</a></li>
                                    <li><a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Patients" asp-action="Index">Patients</a></li>
                                    <li><a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a></li>
                                    @if (User.IsInRole("Admin"))
                                    {
                                       <li><a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                                    }   
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark">Hello, @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Authentication" asp-action="Logout" method="post">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Authentication" asp-action="Login">Log in</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Physiosoft -
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> -
            <a asp-area="" asp-controller="Authentication" asp-action="Signup">Sign Up</a> -
            <a asp-area="" asp-controller="Authentication" asp-action="Login">Login</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>